FROM apache/airflow:2.7.1-python3.11

# Switch to root to prepare directories
USER root
RUN mkdir -p /opt/duckdb/warehouse && chown -R airflow /opt/duckdb/warehouse

# Back to airflow user for runtime
USER airflow
RUN pip install --no-cache-dir duckdb==1.0.0
COPY airflow/requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt
