name: SQLFluff Linting & Formatting

on:
  push:
    paths:
      - '**.sql'
  pull_request:
    paths:
      - '**.sql'

jobs:
  sqlfluff-check:
    name: Lint SQL with SQLFluff
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install SQLFluff
        run: pip install sqlfluff

      # Lint SQL files according to default or project-specific config (.sqlfluff)
      - name: Run SQLFluff lint
        run: sqlfluff lint .

      # (Optional) Check formatting (won't change files, just validate)
      - name: Run SQLFluff format check
        run: sqlfluff format . --check

      # (Optional) If you want auto-formatting in PRs, uncomment:
      # - name: Run SQLFluff fix
      #   run: sqlfluff fix . --force
